kind: pipeline
name: url-shortener

steps:
  - name: build-api
    image: plugins/docker
    settings:
      repo: docker.murbal.me/url-shortener/api
      registry: docker.murbal.me
      dockerfile: ./docker/api/Dockerfile
      username:
        from_secret: docker_registry_user_name
      password:
        from_secret: docker_registry_password
  - name: build-web
    image: plugins/docker
    settings:
      repo: docker.murbal.me/url-shortener/web
      registry: docker.murbal.me
      dockerfile: ./docker/web/Dockerfile
      username:
        from_secret: DOCKER_REGISTRY_USER_NAME
      password:
        from_secret: DOCKER_REGISTRY_PASSWORD
      SERVER_PORT:
        from_secret: SERVER_PORT
      API_SERVER_PORT:
        from_secret: API_SERVER_PORT
      API_SERVICE_HOST:
        from_secret: API_SERVICE_HOST
      API_SERVICE_PORT:
        from_secret: API_SERVICE_PORT
  - name: build-keydb
    image: plugins/docker
    settings:
      repo: docker.murbal.me/url-shortener/keydb
      registry: docker.murbal.me
      dockerfile: ./docker/keydb/Dockerfile
      username:
        from_secret: DOCKER_REGISTRY_USER_NAME
      password:
        from_secret: DOCKER_REGISTRY_PASSWORD
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: murbal.me
      username: root
      password:
        from_secret: SSH_ROOT_PASSWORD
      DOCKER_REGISTRY_USER_NAME:
        from_secret: DOCKER_REGISTRY_USER_NAME
      DOCKER_REGISTRY_PASSWORD:
        from_secret: DOCKER_REGISTRY_PASSWORD
      KEYDB_PASSWORD:
        from_secret: KEYDB_PASSWORD
      KEYDB_HOST:
        from_secret: KEYDB_HOST
      KEYDB_PORT:
        from_secret: KEYDB_PORT
      script:
        - docker network create url-shortener
        - echo "${DOCKER_REGISTRY_PASSWORD}" | docker login docker.murbal.me --username ${DOCKER_REGISTRY_USER_NAME} --password-stdin
        - docker pull docker.murbal.me/url-shortener/api
        - docker pull docker.murbal.me/url-shortener/web
        - docker pull docker.murbal.me/url-shortener/keydb
        - docker run -d --network url-shortener --name url-shortener-keydb -e KEYDB_PASSWORD url-shortener/keydb
        - docker run -d --network url-shortener --name url-shortener-api -e KEYDB_PASSWORD -e KEYDB_HOST -e KEYDB_PORT -p 127.0.0.1:4000:8101 url-shortener/api
        - docker run -d --network url-shortener --name url-shortener-web -p 127.0.0.1:80:8100 url-shortener/web
